# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_platnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'historie platnosci',
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('wartosc', models.FloatField(default=0.0)),
                ('czestotliwosc', models.IntegerField(default=1)),
                ('dlugosc', models.FloatField(default=None)),
                ('id_uslugi', models.ForeignKey(db_column='id_uslugi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='katalog.Usluga')),
            ],
            options={
                'verbose_name_plural': 'platnosci',
            },
        ),
        migrations.AddField(
            model_name='historia_platnosci',
            name='id_uslugi',
            field=models.ForeignKey(db_column='id_uslugi', on_delete=django.db.models.deletion.CASCADE, to='katalog.Usluga'),
        ),
        migrations.AlterUniqueTogether(
            name='historia_platnosci',
            unique_together=set([('id_uslugi', 'data')]),
        ),
    ]
