# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_platnosci',
            fields=[
                ('id_uslugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='katalog.Usluga')),
                ('kwota', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'historie platnosci',
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id_uslugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='katalog.Usluga')),
                ('wartosc', models.FloatField(default=0.0)),
                ('czestotliwosc', models.IntegerField(default=1)),
                ('dlugosc', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'platnosci',
            },
        ),
    ]
