# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalnewartosci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oprocentowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprocentowanie', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id_uslugi', models.CharField(default='US', max_length=500, primary_key=True, serialize=False)),
                ('typ_uslugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalnewartosci.TypUslugi')),
            ],
        ),
        migrations.CreateModel(
            name='Wartosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc_t', models.FloatField(default=0.0)),
                ('wartosc_0', models.FloatField(default=0.0)),
                ('id_uslugi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.Usluga')),
            ],
        ),
        migrations.AddField(
            model_name='oprocentowanie',
            name='id_uslugi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.Usluga'),
        ),
        migrations.AddField(
            model_name='oprocentowanie',
            name='st_rynkowa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalnewartosci.Stopa_rynkowa'),
        ),
    ]
