# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalnewartosci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id_uslugi', models.CharField(default='US', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['typ_uslugi'],
                'verbose_name_plural': 'uslugi',
            },
        ),
        migrations.CreateModel(
            name='Oprocentowanie',
            fields=[
                ('oprocentowanie', models.FloatField(default=0.0)),
                ('id_uslugi', models.ForeignKey(db_column='id_uslugi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='katalog.Usluga')),
                ('st_rynkowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalnewartosci.Stopa_rynkowa')),
            ],
            options={
                'ordering': ['id_uslugi'],
                'verbose_name_plural': 'oprocentowanie',
            },
        ),
        migrations.CreateModel(
            name='Wartosc',
            fields=[
                ('wartosc_t', models.FloatField(default=0.0)),
                ('wartosc_0', models.FloatField(default=0.0)),
                ('id_uslugi', models.ForeignKey(db_column='id_uslugi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='katalog.Usluga')),
            ],
            options={
                'ordering': ['id_uslugi'],
                'verbose_name_plural': 'wartosci',
            },
        ),
        migrations.AddField(
            model_name='usluga',
            name='typ_uslugi',
            field=models.ForeignKey(db_column='typ_uslugi', on_delete=django.db.models.deletion.CASCADE, to='globalnewartosci.TypUslugi'),
        ),
    ]
