# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id_klienta', models.CharField(default='KL', max_length=500, primary_key=True, serialize=False)),
                ('imie', models.CharField(default=None, max_length=50)),
                ('nazwisko', models.CharField(default=None, max_length=50)),
                ('pesel', models.BigIntegerField(default=None, unique=True)),
                ('adres', models.CharField(default=None, max_length=500)),
            ],
            options={
                'ordering': ['nazwisko'],
                'verbose_name_plural': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='klient.Klient')),
                ('email', models.CharField(default=None, max_length=50)),
            ],
            options={
                'ordering': ['id_klienta'],
                'verbose_name_plural': 'e-mail',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='klient.Klient')),
                ('numer_telefonu', models.BigIntegerField(default=None)),
            ],
            options={
                'ordering': ['id_klienta'],
                'verbose_name_plural': 'telefony',
            },
        ),
    ]
