# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id_klienta', models.CharField(default='KL', max_length=500, primary_key=True, serialize=False)),
                ('imie', models.CharField(default=None, max_length=50)),
                ('nazwisko', models.CharField(default=None, max_length=50)),
                ('pesel', models.BigIntegerField(default=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', models.BigIntegerField(default=None)),
                ('numer', models.CharField(default=None, max_length=50)),
                ('ulica', models.CharField(default=None, max_length=50)),
                ('miasto', models.CharField(default=None, max_length=50)),
                ('kod_pocztowy', models.CharField(default=None, max_length=6)),
                ('panstwo', models.CharField(default=None, max_length=50)),
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klient.Klient')),
            ],
        ),
    ]
