# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50)),
            ],
            options={
                'ordering': ['id_klienta'],
                'verbose_name_plural': 'e-mail',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id_klienta', models.CharField(default='KL', max_length=50, primary_key=True, serialize=False)),
                ('imie', models.CharField(default=None, max_length=50)),
                ('nazwisko', models.CharField(default=None, max_length=50)),
                ('pesel', models.BigIntegerField(unique=True)),
                ('adres', models.CharField(default=None, max_length=250)),
            ],
            options={
                'ordering': ['nazwisko'],
                'verbose_name_plural': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', models.CharField(default=None, max_length=50)),
                ('id_klienta', models.ForeignKey(db_column='id_klienta', on_delete=django.db.models.deletion.CASCADE, to='klient.Klient')),
            ],
            options={
                'ordering': ['id_klienta'],
                'verbose_name_plural': 'telefony',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='id_klienta',
            field=models.ForeignKey(db_column='id_klienta', on_delete=django.db.models.deletion.CASCADE, to='klient.Klient'),
        ),
        migrations.AlterUniqueTogether(
            name='telefon',
            unique_together=set([('id_klienta', 'numer_telefonu')]),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('id_klienta', 'email')]),
        ),
    ]
