# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', models.BigIntegerField(default=None)),
                ('numer', models.CharField(default=None, max_length=50)),
                ('ulica', models.CharField(default=None, max_length=50)),
                ('miasto', models.CharField(default=None, max_length=50)),
                ('kod_pocztowy', models.CharField(default=None, max_length=6)),
                ('panstwo', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='klient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='uzytkownik',
        ),
        migrations.AddField(
            model_name='klient',
            name='id_klienta',
            field=models.CharField(default='KL', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='klient',
            name='imie',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='klient',
            name='pesel',
            field=models.BigIntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='id_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klient.Klient', to_field='Klient.id_klienta'),
        ),
    ]
