# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stopa_rynkowa',
            fields=[
                ('st_rynkowa', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'stopa rynkowa',
            },
        ),
        migrations.CreateModel(
            name='TypUslugi',
            fields=[
                ('typ_uslugi', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'typ uslugi',
            },
        ),
    ]
